### PR TITLE
Add pika-network.net & jartexnetwork.com

### PR DESCRIPTION
**Pull request by Naibuu**
Added `play.pika-network.net` and `play.jartexnetwork.com`.

### CODE REVIEW

**Review by ShonP40 — CHANGES_REQUESTED** [review]
Please revert all the changes you’ve done to the `index.json` file as it’s being generated automatically

**Comment by ShonP40** [comment]
Also, next time only open a PR for a single server.

**Comment by Naibuu** [comment]
> Also, next time only open a PR for a single server.

Aight good to know

**Comment by ShonP40** [comment]
You didn't revert that file completely

**Review by ShonP40 — CHANGES_REQUESTED** [review]

**Review by ShonP40 — APPROVED** [review]

**Review by Tellinq — APPROVED** [review]

**Pull request merged**
